
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    name: rabbitmq
    tier: db
spec:
  containers:
  - image: rabbitmq
    name: rabbitmq
    ports:
    - containerPort: 5672
    - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    name: rabbitmq
    tier: db
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: http