---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
data:
  MONGO_URL: "http://mongodb:80"
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    name: catalogue
    tier: app
spec:
  containers:
  - image: techworldwithsiva/catalogue:v1
    name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    name: catalogue
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080