---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  MONGO_URL: "mongodb://mongodb:80/user"
  REDIS_HOST: "redis"
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  namespace: roboshop
  labels:
    name: user
    tier: app
spec:
  containers:
  - image: techworldwithsiva/user:v1
    name: user
    envFrom:
    - configMapRef:
        name: user-config
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    name: user
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080