---
apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: roboshop
  labels:
    name: web
    tier: frontend
spec:
  containers:
  - image: techworldwithsiva/web:k8
    name: web
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    name: mongodb
    tier: db
spec:
  containers:
  - image: techworldwithsiva/mongodb:v1
    name: mongodb
---
apiVersion: v1
kind: Pod
metadata:
  name: almalinux
  namespace: roboshop
  labels:
    name: almalinux
    tier: db
spec:
  containers:
  - image: almalinux
    name: almalinux
    command: ["sleep","10000"]
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: roboshop
  annotations:
    kubernetes.io/ingress.class: alb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    name: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80