---
apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: roboshop
  labels:
    name: web
    tier: frontend
spec:
  containers:
  - image: techworldwithsiva/web:k8
    imagePullPolicy: Always
    name: web
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    name: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80